### ISSUE TITLE
这个命令行补全插件是什么？

### ISSUE THREAD

**Issue by harisonkhlil** [HUAHUAI23/nvim64#3]
如图：
<img width="336" alt="image" src="https://user-images.githubusercontent.com/70578017/193466086-69e9100f-8328-4435-a69e-11291e74c1d1.png">

每次输入命令都要完全和补全命令一样才可以<CR>，另外输入类似:q!这种补全没有的命令就可以直接 Enter
如何调整，或者说补全的插件是哪个?

**Comment by HUAHUAI23** [comment]
命令补全用的cmp https://github.com/hrsh7th/nvim-cmp，默认tab 和shift tab键 上下移动补全选项，<space>e（空格+e）关闭补全，ctrl-<space>触发补全，对于你那种情况 你可以直接<space>e关闭补全

**Comment by HUAHUAI23** [comment]
命令补全用的cmp https://github.com/hrsh7th/nvim-cmp，默认tab 和shift+tab键 上下移动补全选项 <space>+e（空格+e）关闭补全，ctrl+<space>触发补全，对于你那种情况 你可以直接<space>+e关闭补全

**Comment by harisonkhlil** [comment]
找到这个是哪个补全的插件了 `cmp-cmdline`,注释掉这个插件和 `cmp.setup.cmdline` 相关代码就没有强制选择了。
这是效果：
<img width="398" alt="image" src="https://user-images.githubusercontent.com/70578017/193512612-603a9ab4-4e4d-4c9d-a8d9-5e4195899f59.png">

**Comment by HUAHUAI23** [comment]
是的 那个是命令行的补全
可以 快捷键 space-e 就关闭了
https://user-images.githubusercontent.com/43649186/193513304-56bb0943-d80d-421e-8468-47f37d1aafe9.mp4

快捷键设置在 keybingAlias这个文件里
![image](https://user-images.githubusercontent.com/43649186/193513448-9e0327b0-0f77-4f45-820f-4768d09bfb20.png)
