### ISSUE TITLE
请问您的自定义header是怎么生成的?

### ISSUE THREAD

**Issue by est7** [HUAHUAI23/nvim64#4]
就是那个HUAHUA,好看,想有一个

**Comment by thexx9** [comment]
看着这个[https://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20](url)

**Comment by HUAHUAI23** [comment]
对 我是在这个网站生成的

**Comment by est7** [comment]
谢谢,昨天找到了两个
https://texteditor.com/ascii-art/
https://texteditor.com/ascii-art/
