### ISSUE TITLE
下载打包好插件的版本初始化报错

### ISSUE THREAD

**Issue by rainmakerMa** [HUAHUAI23/nvim64#5]
![image](https://user-images.githubusercontent.com/19238174/203896396-09ad1df1-a2e9-461b-af87-5c2fb94d6b90.png)
如图，安装带了插件的版本以后初始化报错
另外想请问下，怎么解决gitgub下载插件的时候超时，无响应的问题，貌似我用代理的镜像地址也不行，试了好几个博主的配置都有类似问题

**Comment by HUAHUAI23** [comment]
好久没更新了，我待会更新下试试，下载超时的话我记得可以通过设置packer，来配置国内的GitHub镜像地址，[neovim.conf](https://github.com/HUAHUAI23/myneovimlua)  这个库是最新的配置

**Comment by rainmakerMa** [comment]
嗯嗯，请问下有没有那种没有外网环境下，插件都已经下载好的离线安装包呐，可以offline安装的

**Comment by HUAHUAI23** [comment]
我重新打包一下试试

**Comment by HUAHUAI23** [comment]
新打包的应该欧克了，你试试
https://github.com/HUAHUAI23/nvim64/releases/download/v2.0/nvim64.tar.gz
