### ISSUE TITLE
你好我是mac系统 sysint.vim没法放进/urc/share里

### ISSUE THREAD

**Issue by Xxh-v** [HUAHUAI23/nvim64#6]
请问有init.rua之类的配置文件吗

**Comment by Xxh-v** [comment]
mac系统那几个文件不让修改权限 sudo也不行 TT

**Comment by HUAHUAI23** [comment]
> 请问有init.rua之类的配置文件吗

有的  看这个库 https://github.com/HUAHUAI23/myneovimlua

**Comment by HUAHUAI23** [comment]
> mac系统那几个文件不让修改权限 sudo也不行 TT

不需要的呀 哦 你是用的包管理器装的 nvim对吧，不是 二进制直接就可以跑的那个版本对吧，如果是二进制那个版本所有的东西全在一个目录下，和系统的目录结构是没有关系的

**Comment by Xxh-v** [comment]
好滴 非常感谢
