### ISSUE TITLE
Might I ask you something about nvim-dap + cpptools?

### ISSUE THREAD

**Issue by nyngwang** [HUAHUAI23/nvim64#8]
Say I'm on macOS, do the following lines (`miDebuggerPath = "/usr/bin/gdb", ` specifically) assume a system-wise `gdb`? I'm confused because of that I use mason.nvim to install `cpptools` and it also includes lldb-mi, which seems to be an alternative of gdb. But currently lldb-mi causes some errors.

https://github.com/HUAHUAI23/nvim64/blob/64fe13b5329ddafd919f2a4b9689bdd9d45fea43/runtime/lua/dap/nvim-dap/config/cpptools.lua#L7-L30

**Comment by nyngwang** [comment]
Closing as my conclusion is that we should always prefer using codelldb for debugging Cpp/C/Rust in Neovim. More easy to setup and less problematic after the termination of the debugging session.

**Comment by HUAHUAI23** [comment]
> 

Right. System-wide gdb.

**Comment by HUAHUAI23** [comment]
> Say I'm on macOS, do the following lines (`miDebuggerPath = "/usr/bin/gdb", ` specifically) assume a system-wise `gdb`? I'm confused because of that I use mason.nvim to install `cpptools` and it also includes lldb-mi, which seems to be an alternative of gdb. But currently lldb-mi causes some errors.
> 
> https://github.com/HUAHUAI23/nvim64/blob/64fe13b5329ddafd919f2a4b9689bdd9d45fea43/runtime/lua/dap/nvim-dap/config/cpptools.lua#L7-L30

Right. System-wide gdb, it from It comes from the example file https://github.com/mfussenegger/nvim-dap/wiki/C-C---Rust-(gdb-via--vscode-cpptools)
